version: '2'
services:
  #######################################
  # PHP application Docker container
  #
  # for this container you have to remove
  # following entries from .dockerignore:
  #
  # etc/*
  # provision/*
  # app/*
  #
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile.cloud
    links:
      - mysql
      #- postgres
      #- mail
      #- solr
      #- elasticsearch
      #- redis
      #- memcached
      #- ftp
    restart: always
    ports:
      - "8000:80"
      - "8443:443"
      - "10022:22"
    volumes_from:
      - storage
    env_file:
      - etc/base.env
      - etc/production.env

  #######################################
  # MySQL server
  #######################################
  mysql:
    build:
      context: docker/mysql/
      #dockerfile: MySQL-5.5.Dockerfile
      dockerfile: MySQL-5.6.Dockerfile
      #dockerfile: MySQL-5.7.Dockerfile
      #dockerfile: MariaDB-5.5.Dockerfile
      #dockerfile: MariaDB-10.Dockerfile
      #dockerfile: Percona-5.5.Dockerfile
      #dockerfile: Percona-5.6.Dockerfile
      #dockerfile: Percona-5.7.Dockerfile
    restart: always
    volumes_from:
      - storage
    env_file:
      - etc/base.env
      - etc/production.env

  #######################################
  # PostgreSQL server
  #######################################
  #postgres:
  #  build:
  #    context: docker/postgres/
  #    dockerfile: Postgres-9.4.Dockerfile
  #    dockerfile: Postgres-9.5.Dockerfile
  #  restart: always
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/base.env
  #    - etc/production.env

  #######################################
  # Solr server
  #######################################
  #solr:
  #  build:
  #    #context: docker/solr/ext-solr-3.0/
  #    #context: docker/solr/ext-solr-3.1/
  #    #context: docker/solr/ext-solr-4.0-5.0/
  #    context: docker/solr/ext-solr-5.1/
  #  restart: always
  #  volumes_from:
  #    - storage
  #  environment:
  #    - SOLR_STORAGE=/storage/solr/server-master/
  #  env_file:
  #    - etc/base.env
  #    - etc/production.env

  #######################################
  # Elasticsearch
  #######################################
  #elasticsearch:
  #  build:
  #    context: docker/elasticsearch/
  #  restart: always
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/base.env
  #    - etc/production.env

  #######################################
  # Redis
  #######################################
  #redis:
  #  build:
  #    context: docker/redis/
  #  restart: always
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/base.env
  #    - etc/production.env

  #######################################
  # Memcached
  #######################################
  #memcached:
  #  build:
  #    context: docker/memcached/
  #  restart: always
  #  volumes_from:
  #    - storage
  #  env_file:
  #    - etc/base.env
  #    - etc/production.env

  #######################################
  # FTP (vsftpd)
  #######################################
  #ftp:
  #  build:
  #    context: docker/vsftpd/
  #  restart: always
  #  volumes_from:
  #    - sourcecode
  #    - storage
  #  env_file:
  #    - etc/base.env
  #    - etc/production.env

  #######################################
  # Storage
  #######################################
  storage:
    build:
      context: docker/storage/
    restart: always
    volumes:
      - /storage
